version: '3.8'
services:
  client:
    build: ./client/
    env_file:
      - ./client/.env
    ports:
      - "3056:3000"
    restart: unless-stopped
    networks:
      - ecomerce_net
  app:
    build: ./server/.
    ports:
      - "5654:8080"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_MAIL_HOST=smtp-service
      - SPRING_MAIL_PORT=1025
      - UPLOAD_DIR=/app/uploads/images
    entrypoint: >
      sh -c "
        mkdir -p /app/uploads/images &&
        chown -R 1000:1000 /app/uploads &&
        chmod -R 755 /app/uploads &&
        su-exec 1000:1000 java -jar /app/app.jar
      "
    volumes:
      - uploads_volume:/app/uploads
    networks:
      - ecomerce_net
    depends_on:
      - smtp-service

  # Добавляем новый сервис для отправки почты
  smtp-service:
    image: maildev/maildev
    container_name: smtp-service
    restart: unless-stopped
    environment:
      - NODE_OPTIONS=--no-warnings=DeprecationWarning
      - DEBUG=maildev*
    env_file:
      - ./server/.env
    command:
      --outgoing-host smtp.gmail.com
      --outgoing-port 465
      --outgoing-secure
      --outgoing-user mailer7012@gmail.com
      --outgoing-pass "ldxm ypzz ewvf mnwq"
      --auto-relay
      --verbose
    ports:
      - "8180:1080"
    networks:
      - ecomerce_net

networks:
  ecomerce_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  uploads_volume:
    driver: local
